[workspace]

# Currently there are conflicting deps in the repos.
members = [
    "u2fframing",
    "bitbox-bridge",
    "hidapi-async",
]


[profile.release]
lto = true
#debug = 1
incremental = false
